version: '3'
services:
    php:
        build:
            context: ./docker
            dockerfile: php.Dockerfile
        container_name: ${APP_NAME:?err}-php
        volumes:
            - './app:/var/www/html'

    nginx-vuln:
        build:
            context: ./docker
            dockerfile: nginx-vuln.Dockerfile
        container_name: ${APP_NAME:?err}-nginx-vuln
        ports:
            - '443:443'
        links:
            - 'php'
        volumes:
            - './app:/var/www/html'
            - './config/nginx-vuln:/etc/nginx/conf.d'
            - './ca:/etc/ca'
    
    nginx:
        image: nginx:1.25.3
        container_name: ${APP_NAME:?err}-nginx
        ports:
            - '444:443'
        links:
            - 'php'
        volumes:
            - './app:/var/www/html'
            - './config/nginx:/etc/nginx/conf.d'
            - './ca:/etc/ca'