version: '3'
services:
    php:
        # image: 'php:8.2-fpm'
        build:
            context: ./docker
            dockerfile: php.Dockerfile
        container_name: ${APP_NAME:?err}-php
        volumes:
            - './app:/var/www/html'

    nginx:
        image: nginx:1.25.3
        container_name: ${APP_NAME:?err}-nginx
        ports:
            - '80:80'
            - '443:443'
        links:
            - 'php'
        volumes:
            - './app:/var/www/html'
            - './config/nginx:/etc/nginx/conf.d'
            - './ca:/etc/ca'